version: '3.7'

services:
  webhook:
    build: .
    container_name: webhook
    command: -verbose -hooks=hooks.json -hotreload
    volumes:
      - ./sampleHook:/config:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9001:9000'
    restart: always    