name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    -         
      name: Checkout
      uses: actions/checkout@v3
    - 
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2.4.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: heg0dmsk/webhook-docker
        short-description: ${{ github.event.repository.description }}
