name: Scan Docker Image
on:
  workflow_dispatch:

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    -         
      name: Checkout
      uses: actions/checkout@v2.3.4
    - 
      name: Docker Image Scan
      uses: azure/container-scan@v0
      with:
        image-name: heg0dmsk/webhook-docker
